version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abylay961388
    networks:
      - network-backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    #    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - POSTGRES_NAME=postgres2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abylay961388
    depends_on:
      - db
    networks:
      - network-backend
networks:
  network-backend:
    external: true
