# Generated by Django 3.2.13 on 2022-09-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220930_0009'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='mainuser_ptr',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
