# Generated by Django 3.2.16 on 2022-11-20 17:34

import auth_.models
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_alter_mainuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('mainuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_.mainuser')),
                ('salary', models.PositiveIntegerField(default=0)),
                ('review', models.PositiveIntegerField(default=0, validators=[utils.validators.validate_review])),
            ],
            options={
                'verbose_name': 'courier',
                'verbose_name_plural': 'couriers',
            },
            bases=('auth_.mainuser',),
            managers=[
                ('objects', auth_.models.MainUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('mainuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_.mainuser')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='salary')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
            bases=('auth_.mainuser',),
            managers=[
                ('objects', auth_.models.MainUserManager()),
            ],
        ),
    ]
